### ISSUE TITLE
 missing required args

### ISSUE THREAD

**Issue by WuglyakBolgoink** [itwillwork/ostap#3]
It will be better to use default path for `./package.json` and show error if file was not found in same folder

```bash
$ ostap -s
```

to avoid error like this:

```
error: missing required args for command `<file>`
```

**Comment by itwillwork** [comment]
Thanks! good idea
https://github.com/itwillwork/ostap/commit/2d7989c3ae5e3fc30de931a4b64f000dda5360a9
```
npm i -g ostap@1.0.3
```
