### ISSUE TITLE
Output in ostap -d

### ISSUE THREAD

**Issue by WuglyakBolgoink** [itwillwork/ostap#5]
![image](https://user-images.githubusercontent.com/2271337/55463167-c2cd5e00-55f8-11e9-99cb-1db3356d454f.png)

**Comment by itwillwork** [comment]
thank you for your feedback!
https://github.com/itwillwork/ostap/commit/507e09205c672af42bde8b16b76429645e016a18
https://github.com/itwillwork/ostap/commit/6f5391fb26f7b1d95d02ad6871ad7bbebea8207e
```
npm i -g ostap@1.0.4
```
